server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/oncaner/microservice-config-server.git"
          default-label: "main"     # branch name
          skip-ssl-validation: true
          username: "oncaner"
          password: ${GIT_KEY}      # Environment Variable