server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/AuthDB
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
